# Generated by Django 6.0.7 on 2026-08-26 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_master', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitystaff',
            name='assigned_block',
        ),
        migrations.AlterField(
            model_name='resident',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residents', to='apartment_master.flat'),
        ),
    ]
