# Generated by Django 6.0.7 on 2026-08-19 02:49

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_sqft_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('water_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('parking_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sinking_fund', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('grace_period_days', models.PositiveIntegerField(default=0)),
                ('late_fee_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maximum_late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
