# Generated by Django 6.0.7 on 2026-08-19 03:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_month', models.DateField()),
                ('due_date', models.DateField()),
                ('base_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('area_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('water_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('parking_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sinking_fund', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('principal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='GENERATED', max_length=20)),
                ('generated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
