# Generated by Django 6.0.7 on 2026-07-31 16:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('name', models.CharField(help_text='Examples: 1BHK, 2BHK, Studio, Duplex', max_length=50, unique=True, verbose_name='Flat Type')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Flat Type',
                'verbose_name_plural': 'Flat Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('name', models.CharField(max_length=255, verbose_name='Society Name')),
                ('registration_number', models.CharField(help_text='Society/RERA registration number', max_length=100, unique=True, verbose_name='Registration Number')),
                ('address_line1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Society',
                'verbose_name_plural': 'Societies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Wing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('name', models.CharField(help_text='Unique wing identifier (e.g. A, B, C).', max_length=50, verbose_name='Wing')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wings', to='apartment_master.society', verbose_name='Society')),
            ],
            options={
                'verbose_name': 'Wing',
                'verbose_name_plural': 'Wings',
                'ordering': ['society', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('floor_number', models.SmallIntegerField(help_text='0 = Ground floor. Negative values represent basements.', verbose_name='Floor Number')),
                ('name', models.CharField(blank=True, help_text="Optional human label, e.g. 'Ground', 'Mezzanine'", max_length=50, verbose_name='Floor Name')),
                ('wing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='floors', to='apartment_master.wing', verbose_name='Wing')),
            ],
            options={
                'verbose_name': 'Floor',
                'verbose_name_plural': 'Floors',
                'ordering': ['wing', 'floor_number'],
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('flat_number', models.CharField(help_text="e.g. '101', '101-A'", max_length=20, verbose_name='Flat Number')),
                ('carpet_area_sqft', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Carpet Area (sqft)')),
                ('built_up_area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Built-up Area (sqft)')),
                ('facing', models.CharField(blank=True, choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West'), ('NE', 'North-East'), ('NW', 'North-West'), ('SE', 'South-East'), ('SW', 'South-West')], max_length=2, verbose_name='Facing')),
                ('flat_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flats', to='apartment_master.flattype', verbose_name='Flat Type')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flats', to='apartment_master.floor', verbose_name='Floor')),
            ],
            options={
                'verbose_name': 'Flat',
                'verbose_name_plural': 'Flats',
                'ordering': ['floor', 'flat_number'],
                'indexes': [models.Index(fields=['floor', 'flat_number'], name='idx_flat_floor_number'), models.Index(fields=['flat_number'], name='idx_flat_number')],
                'constraints': [models.UniqueConstraint(fields=('floor', 'flat_number'), name='uniq_flat_number_per_floor'), models.CheckConstraint(condition=models.Q(('carpet_area_sqft__gt', 0)), name='chk_flat_carpet_area_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='wing',
            index=models.Index(fields=['society', 'name'], name='idx_wing_society_name'),
        ),
        migrations.AddConstraint(
            model_name='wing',
            constraint=models.UniqueConstraint(fields=('society', 'name'), name='uniq_wing_name_per_society'),
        ),
        migrations.AddIndex(
            model_name='floor',
            index=models.Index(fields=['wing', 'floor_number'], name='idx_floor_wing_number'),
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('wing', 'floor_number'), name='uniq_floor_number_per_wing'),
        ),
    ]
