# Generated by Django 6.0.7 on 2026-08-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(default="HDFC Bank, Baner Branch", max_length=200),
                ),
                (
                    "account_number",
                    models.CharField(
                        default="50200067281234", max_length=50, unique=True
                    ),
                ),
                ("ifsc_code", models.CharField(default="HDFC0001234", max_length=20)),
                (
                    "account_type",
                    models.CharField(default="Current Account", max_length=50),
                ),
                ("is_primary", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BillingSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_prefix", models.CharField(default="RCP", max_length=10)),
                ("starting_no", models.PositiveIntegerField(default=2024001)),
                ("bill_prefix", models.CharField(default="BILL", max_length=10)),
                ("financial_year", models.CharField(default="2024-25", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="NotificationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sms_notifications", models.BooleanField(default=True)),
                ("email_notifications", models.BooleanField(default=True)),
                ("whatsapp_notifications", models.BooleanField(default=False)),
                ("payment_reminders", models.BooleanField(default=True)),
                ("overdue_alerts", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SocietyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Epsilon Homes", max_length=255)),
                (
                    "registration_no",
                    models.CharField(default="MAH/2015/EPH-001", max_length=100),
                ),
                (
                    "address",
                    models.TextField(default="Survey No. 45, Baner Road, Baner"),
                ),
                ("city", models.CharField(default="Pune", max_length=100)),
                ("state", models.CharField(default="Maharashtra", max_length=100)),
                ("pin_code", models.CharField(default="411045", max_length=10)),
                ("phone", models.CharField(default="+91 20 2560 8800", max_length=20)),
                (
                    "email",
                    models.EmailField(default="admin@epsilonhomes.in", max_length=254),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Society Info",
            },
        ),
        migrations.CreateModel(
            name="SystemNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("PAYMENT_RECEIVED", "Payment Received"),
                            ("OVERDUE_ALERT", "Overdue Alert"),
                            ("SOCIETY_AGM", "Society AGM"),
                            ("BILLS_GENERATED", "Bills Generated"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
