# Generated by Django 6.0.7 on 2026-08-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='societyinfo',
            table='society_info',
        ),
    ]
