# Generated by Django 6.0.7 on 2026-07-29 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(db_index=True, max_length=6)),
                ('purpose', models.CharField(choices=[('LOGIN', 'Login'), ('REGISTER', 'Register'), ('FORGOT_PASSWORD', 'Forgot Password')], max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_otps',
                'ordering': ['-created_at'],
            },
        ),
    ]
